apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-roeb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-myfn-tenant/rhtap-demo-app/hacbs-test-project-roeb@sha256:c1ad43cf2d27103602cdce89767f9fe1bb2d0fc1bba7313fd8f7f5f620ff5d5f
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
