apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-roeb
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-myfn-tenant/rhtap-demo-app/hacbs-test-project-roeb@sha256:5599d42b1bebfea8c33a40c53d88e29543bb188aaea4bf8ca3ad054a967fab02
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
