apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-roeb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-roeb
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-roeb
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-roeb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-roeb
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-myfn-tenant/rhtap-demo-app/hacbs-test-project-roeb@sha256:c1ad43cf2d27103602cdce89767f9fe1bb2d0fc1bba7313fd8f7f5f620ff5d5f
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
